import { makeStyles } from '@material-ui/core/styles'

export const rewardsStyles = makeStyles(theme => ({
  impactSection: {
    borderRadius: theme.spacing(1),
    padding: theme.spacing(2),
    display: 'flex',
    alignItems: 'center',
    position: 'relative',
    cursor: 'pointer',
  },
  impactSectionSavedCards: {
    backgroundColor: '#5db300',
  },
  impactSectionGreenhouseGases: {
    backgroundColor: '#3483e5',
  },
  impactSectionTrees: {
    backgroundColor: '#966C40',
  },
  impactSectionWater: {
    backgroundColor: '#00bbbb',
  },
  impactSectionIcon: {
    marginRight: theme.spacing(2),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 80,
    height: 80,
    backgroundColor: 'rgba(0,0,0,0.25)',
    borderRadius: 100,
    '& svg': {
      fontSize: '3rem',
    },
  },
  impactSectionNumber: {
    fontWeight: 700,
    color: '#fff',
    fontSize: '2rem',
    lineHeight: 'initial',
    '& span': {
      fontSize: '0.8rem',
      marginLeft: theme.spacing(0.5),
    },
  },
  impactSectionTitle: {
    color: '#fff',
    textTransform: 'capitalize',
    fontSize: '0.8rem',
    fontWeight: 300,
  },
  impactSectionInfoIcon: {
    position: 'absolute',
    right: theme.spacing(2),
    top: theme.spacing(2),
    color: '#fff',
    opacity: 0.75,
    fontSize: '1.2rem',
  },
  milestonesContainer: {
    position: 'relative',
    '&:after': {
      position: 'absolute',
      left: 13,
      top: 0,
      height: '100%',
      width: 8,
      content: '""',
      backgroundColor: '#00C49F',
      borderRadius: 20,
    },
  },
  milestoneBox: {
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    position: 'relative',
    zIndex: 1,
    width: '100%',
    paddingTop: theme.spacing(2),
    paddingBottom: theme.spacing(2),
    marginBottom: theme.spacing(2),
  },
  milestoneIndicatorIconContainerClaimed: {},
  milestoneIndicatorIconContainer: {
    backgroundColor: theme.palette.background.default,
    border: `1px dashed ${theme.palette.background.dark}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: theme.palette.background.reverse,
    width: 35,
    height: 35,
    borderRadius: '50%',
    '& svg': {
      fontSize: '1rem',
    },
    '&$milestoneIndicatorIconContainerClaimed': {
      backgroundColor: '#00C49F',
      border: `2px solid ${theme.palette.background.default}`,
      '& svg': {
        color: '#fff',
      },
    },
  },
  milestoneCardClaimed: {},
  milestoneCard: {
    backgroundColor: theme.palette.background.light,
    padding: theme.spacing(2),
    borderRadius: theme.spacing(2),
    marginLeft: theme.spacing(1),
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    flex: 'auto',
    gap: theme.spacing(1),
    '&$milestoneCardClaimed': {
      border: '2px solid #00C49F',
    },
  },
  milestoneButtonClaimed: {},
  milestoneButtonUnclaimed: {},
  milestoneData: {
    color: theme.palette.background.reverse,
    textAlign: 'left',
    '& button': {
      marginLeft: 0,
      marginRight: 0,
      marginBottom: 0,
      marginTop: theme.spacing(2),
      '&$milestoneButtonClaimed': {
        backgroundColor: '#00C49F !important',
        color: '#fff !important',
        border: '1px solid #00C49F !important',
      },
      '&$milestoneButtonUnclaimed': {
        border: 'none !important',
        fontWeight: 400,
        textAlign: 'left',
        paddingLeft: '0 !important',
        paddingRight: '0 !important',
        color: '#5ab527 !important',
      },
    },
  },
  milestoneTitle: {
    fontSize: '1rem',
    fontWeight: 600,
    lineHeight: 'initial',
    marginBottom: theme.spacing(1),
  },
  milestoneDescription: {
    fontSize: '0.8rem',
    fontWeight: 300,
    lineHeight: '1.2rem',
  },
  milestoneProgressContainer: {
    width: 85,
    position: 'relative',
  },
  milestonePercentage: {
    width: 25,
    height: 25,
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    right: 0,
    margin: 'auto',
    fontSize: '0.8rem',
    color: theme.palette.background.reverse,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rewardData: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  codeActionsContainer: {
    gap: theme.spacing(2),
  },
  copyCode: {
    fontWeight: 600,
    fontSize: '1.2rem !important',
    color: '#272727 !important',
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    marginBottom: theme.spacing(1),
    marginTop: theme.spacing(1),
    '& p': {
      fontSize: '1.2rem !important',
      color: '#272727 !important',
      fontWeight: 600,
    },
  },
  copyCodeButton: {
    backgroundColor: '#00C49F !important',
    border: 'none',
    color: '#fff !important',
    textDecoration: 'none',
    borderRadius: theme.spacing(4),
    cursor: 'pointer',
  },
  envImpactContainer: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    height: 400,
    // paddingTop: theme.spacing(4),
    // paddingBottom: theme.spacing(4),
    // paddingRight: theme.spacing(4),
  },
  envImpactFilledArea: {
    height: 10,
    width: 16,
    backgroundColor: '#00C49F',
    borderRadius: '0 0 20px 20px',
  },
  envImpactRoot: {
    height: 16,
    borderRadius: '20px 20px 0 0',
    marginBottom: 0,
    padding: '0 !important',
    margin: '0 !important',
    width: '16px !important',
  },
  envImpactTrack: {
    width: '16px !important',
    height: 2,
    backgroundColor: '#00C49F',
  },
  envImpactRail: {
    width: '16px !important',
    backgroundColor: theme.palette.background.darker,
    borderRadius: '20px 20px 0 0',
    opacity: 1,
  },
  envImpactMark: {
    width: 16,
    height: 2,
    backgroundColor: '#00C49F',
    '&:nth-child(8)': {
      display: 'none',
    },
  },
  envImpactMarkLabel: {
    top: 32,
    fontSize: '0.7rem',
    color: theme.palette.background.reverse,
    width: 65,
    whiteSpace: 'normal',
    textAlign: 'center',
  },
  envImpactThumb: {
    backgroundColor: theme.palette.background.reverse,
  },
  envImpactValueLabel: {
    color: theme.palette.background.reverse,
    left: -45,
    top: -3,
    '& > span': {
      color: theme.palette.background.reverse,
      transform: 'rotate(-135deg)',
      '& span': {
        color: theme.palette.background.default,
        transform: 'rotate(135deg)',
      },
    },
  },
}))
