import { makeStyles } from '@material-ui/core/styles'

export const subscriptionStyles = makeStyles(theme => ({
  shareButtonsContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    '& button': {
      display: 'flex',
      flex: '46%',
      textAlign: 'left',
      marginRight: '2%',
      alignItems: 'center',
      padding: `${theme.spacing(2)}px ${theme.spacing(1)}px !important`,
      borderBottom: `1px solid ${theme.palette.background.dark} !important`,
      '&:last-child': {
        borderBottom: 'none !important',
        paddingBottom: `${theme.spacing(1)}px !important`,
      },
      [theme.breakpoints.down('xs')]: {
        flex: '100%',
        marginRight: 0,
      },
    },
  },
  shareButtonText: {
    marginLeft: theme.spacing(1),
    color: theme.palette.background.reverse,
  },
  icon: {
    color: theme.palette.background.gradient.dark,
  },
  shareFormContainer: {
    backgroundColor: theme.palette.background.light,
    color: theme.palette.background.reverse,
    border: `1px solid ${theme.palette.background.dark}`,
    borderRadius: theme.spacing(1),
    padding: theme.spacing(1),
  },
  pricingHeaderContainer: {
    backgroundColor: '#272727',
    padding: 16,
  },
  pricingHeader: {
    maxWidth: 400,
    margin: '0 auto',
  },
  pricingBackButton: {
    color: '#ffffff',
    '& svg': {
      color: '#ffffff',
    },
  },
  pricingHero: {
    marginTop: 32,
    marginBottom: 12,
    maxWidth: 380,
    margin: '0 auto',
  },
  pricingLogoContainer: {
    margin: '0 32px 16px',
    '& img': {
      maxHeight: 120,
      margin: '0 auto',
      display: 'block',
      borderRadius: 6,
    },
  },
  pricingTitle: {
    color: '#A9A9A9',
    fontWeight: 600,
    fontSize: 16,
  },
  pricingPrice: {
    fontSize: 22,
    color: '#ffffff',
    fontWeight: 700,
    margin: '2px 0 3px',
  },
  pricingTagLine: {
    marginTop: 16,
    marginBottom: 4,
    color: '#A9A9A9',
    fontSize: 14,
  },
  pricingContent: {
    backgroundColor: '#ffffff',
    padding: '24px 16px 90px',
  },
  pricingTable: {
    maxWidth: 380,
    margin: '0 auto',
  },
  pricingFeature: {
    padding: '24px 0',
    borderBottom: '1px solid #ddd',
  },
  pricingFeatureDescription: {
    color: '#1a1a1ab3',
    fontWeight: 600,
    fontSize: 14,
  },
  pricingButtonContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    padding: 12,
    bottom: 0,
    left: 0,
    width: '100%',
    gap: 12,
    backgroundColor: theme.palette.background.light,
    flexDirection: 'row-reverse',
    ['@media (max-width:650px)']: { // eslint-disable-line no-useless-computed-key
      flexDirection: 'column-reverse',
    },
  },
  pricingButton: {
    border: `1px solid ${theme.palette.background.lighter}`,
    position: 'relative',
    minWidth: 300,
    marginTop: 24,
    padding: 24,
    alignItems: 'flex-start',
    borderRadius: theme.spacing(1),
    '& span': {
      display: 'block',
    },
  },
  pricingButtonText: {
    textTransform: 'uppercase',
    color: theme.palette.background.reverse,
  },
  pricingBestValue: {
    backgroundColor: theme.palette.background.light,
    color: theme.palette.background.reverse,
    border: `1px solid ${theme.palette.background.lighter}`,
    fontSize: 10,
    position: 'absolute',
    width: 100,
    top: -10,
    left: 0,
    right: 0,
    margin: 'auto',
    borderRadius: theme.spacing(0.5),
  },
  pricingButtonPeriod: {
    fontSize: 12,
    marginBottom: 20,
  },
  pricingButtonNumber: {
    position: 'relative',
    fontSize: 60,
    fontWeight: 600,
    // width: 130,
    lineHeight: '70px',
    margin: '20px auto 0',
    display: 'inline-block !important',
  },
  pricingButtonCurrencyMonthly: {},
  pricingButtonCurrency: {
    fontSize: 18,
    fontWeight: 400,
    position: 'absolute',
    top: -18,
    left: -18,
    // '&$pricingButtonCurrencyMonthly': {
    //   left: 18,
    // },
  },
  pricingButtonSave: {
    fontSize: 14,
    fontWeight: 600,
    backgroundColor: '#ffb100',
    color: '#272727',
    padding: theme.spacing(0.5),
    borderRadius: `${theme.spacing(0.5)}px ${theme.spacing(0.5)}px 0 0`,
  },
  pricingSelect: {
    backgroundColor: theme.palette.background.reverse,
    color: theme.palette.background.light,
    textAlign: 'center',
    padding: '8px 24px',
    marginTop: 0,
    borderRadius: `0 0 ${theme.spacing(0.5)}px ${theme.spacing(0.5)}px`,
  },
  pricingSafePayment: {
    marginTop: theme.spacing(1),
    textAlign: 'center',
    fontSize: '0.7rem',
    opacity: 0.75,
    textTransform: 'none',
  },
  loadingText: {
    color: '#fff',
    fontSize: '0.8rem',
    maxWidth: 260,
    marginTop: theme.spacing(1),
    fontWeight: 600,
  },
}))
