import { makeStyles } from '@material-ui/core/styles'

export const editCardStyles = makeStyles(theme => ({
  appBar: {
    position: 'relative',
  },
  layout: {
    width: 'auto',
    marginLeft: theme.spacing(2),
    marginRight: theme.spacing(2),
    [theme.breakpoints.up(600 + theme.spacing(2) * 2)]: {
      width: 600,
      marginLeft: 'auto',
      marginRight: 'auto',
    },
  },
  root: {
    color: theme.palette.background.default,
    '& > .MuiBox-root': {
      '& > .MuiBox-root': {
        [theme.breakpoints.down('sm')]: {
          paddingLeft: 0,
          paddingRight: 0,
        },
      },
    },
  },
  paper: {
    marginTop: theme.spacing(3),
    marginBottom: theme.spacing(3),
    padding: theme.spacing(2),
    [theme.breakpoints.up(600 + theme.spacing(3) * 2)]: {
      marginTop: theme.spacing(6),
      marginBottom: theme.spacing(6),
      padding: theme.spacing(3),
    },
    backgroundColor: theme.palette.background.default,
    color: theme.palette.background.reverse,
  },
  stepper: {
    padding: theme.spacing(3, 0, 5),
  },
  buttons: {
    display: 'flex',
    justifyContent: 'flex-end',
  },
  button: {
    marginTop: theme.spacing(3),
    marginLeft: theme.spacing(1),
  },
  editCardTitle: {
    fontSize: '1.5rem',
    color: theme.palette.background.highlight,
    fontWeight: 'bold',
    marginBottom: theme.spacing(2),
  },
  editCardTab: {
    textTransform: 'capitalize',
    [theme.breakpoints.up('sm')]: {
      minWidth: '130px',
    },
  },
  editButtonContainer: {
    marginTop: theme.spacing(3),
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'sticky',
    bottom: theme.spacing(1),
  },
  editCardButton: {
    backgroundColor: theme.palette.background.reverse,
    color: theme.palette.background.default,
    '&:hover': {
      backgroundColor: theme.palette.background.reverse,
      color: theme.palette.background.default,
      opacity: 0.9,
    },
  },
  editCardButtonDisabled: {
    backgroundColor: theme.palette.background.reverse,
    color: `${theme.palette.background.lighter} !important`,
    opacity: 0.5,
  },
  tabContentContainer: {
    '& .MuiBox-root': {
      paddingLeft: 0,
      paddingRight: 0,
    },
  },
}))

export const viewCardStyles = makeStyles(theme => ({
  viewCardContainer: {
    position: 'relative',
  },
  viewCardHero: {
    minHeight: 200,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundImage: `linear-gradient(${theme.palette.background.gradient.light}, ${theme.palette.background.gradient.dark})`,
    paddingTop: theme.spacing(4),
    paddingBottom: theme.spacing(4),
    position: 'relative',
  },
  logoLink: {
    position: 'absolute',
    top: theme.spacing(2),
    left: theme.spacing(2),
  },
  logo: {
    width: 25,
  },
  viewCardHeroInfo: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonGroupContainer: {
    position: 'absolute',
    top: theme.spacing(2),
    right: theme.spacing(2),
    display: 'flex',
    flexDirection: 'row-reverse',
    justifyContent: 'center',
    alignItems: 'center',
    [theme.breakpoints.down('sm')]: {
      position: 'initial',
      marginBottom: theme.spacing(2),
    },
    '& button': {
      backgroundColor: theme.palette.background.gradient.light,
      marginLeft: theme.spacing(1),
    },
  },
  viewCardAvatar: {
    width: 130,
    height: 130,
    margin: '0 auto',
    bottom: '-30px',
    boxShadow: '0 0 25px rgb(0 0 0 / 40%)',
    backgroundColor: '#ffffff',
    [theme.breakpoints.down('sm')]: {
      bottom: '-10px',
    },
  },
  viewCardName: {
    textTransform: 'capitalize',
    fontFamily: theme.fonts.cardTitle.en.family,
    color: theme.palette.background.default,
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: theme.spacing(3),
    [theme.breakpoints.down('sm')]: {
      fontSize: 22,
      marginTop: theme.spacing(3),
    },
    [theme.breakpoints.down('xs')]: {
      marginTop: theme.spacing(5),
    },
  },
  viewCardProtectedTitle: {
    fontSize: '0.8em',
    textAlign: 'center',
    marginBottom: theme.spacing(3),
  },
  viewCardActionsContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
  },
  ViewCardLinksContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    flexWrap: 'wrap',
    maxWidth: 400,
    margin: '0 auto',
  },
  socialLink: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 35,
    height: 35,
    borderRadius: '50%',
    borderWidth: 1,
    borderStyle: 'solid',
    margin: theme.spacing(1),
  },
  addToContactsButton: {
    backgroundColor: theme.palette.background.reverse,
    color: theme.palette.background.default,
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    position: 'absolute',
    left: 0,
    right: 0,
    margin: 'auto',
    bottom: '-15px',
    textTransform: 'none',
    display: 'block',
    maxWidth: '150px',
    textAlign: 'center',
    textDecoration: 'none',
    padding: theme.spacing(1),
    '&:hover': {
      backgroundColor: theme.palette.background.highlight,
    },
  },
  emailContainer: {
    marginTop: theme.spacing(1),
    marginBottom: theme.spacing(2),
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    '& a': {
      textDecoration: 'none',
    },
  },
  notes: {},
  viewCardData: {
    maxWidth: 350,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: theme.spacing(1),
    marginBottom: 0,
    marginLeft: 'auto',
    marginRight: 'auto',
    '& p': {
      borderBottomWidth: 1,
      borderBottomStyle: 'solid',
      borderBottomColor: theme.palette.background.darker,
      width: '100%',
      display: 'flex',
      justifyContent: 'flex-end',
      alignItems: 'center',
      color: theme.palette.background.lighter,
      paddingTop: theme.spacing(0.5),
      paddingBottom: theme.spacing(0.5),
      '&$notes': {
        border: 'none',
        marginTop: theme.spacing(1),
        fontSize: '0.9rem',
        '& span': {
          width: '100%',
        },
      },
      '& span': {
        display: 'block',
        width: '50%',
        marginLeft: theme.spacing(1),
        color: theme.palette.background.reverse,
        '&:first-letter': {
          textTransform: 'uppercase',
        },
      },
      '&:last-of-type': {
        border: 'none',
      },
    },
  },
  linksContainer: {
    width: '100%',
    paddingTop: 0,
    marginTop: theme.spacing(3),
  },
  link: {
    display: 'block',
    color: theme.palette.background.reverse,
    textDecoration: 'none',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: theme.palette.background.darker,
    background: theme.palette.background.darker,
    borderRadius: theme.spacing(1),
    marginBottom: theme.spacing(1),
    '& li': {
      display: 'flex',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
      '& .MuiListItemIcon-root': {
        marginTop: 5,
      },
      '& .MuiListItemText-multiline': {
        margin: 0,
        '& span': {
          textTransform: 'capitalize',
        },
      },
    },
    '& p': {
      border: 'none',
      display: 'block',
    },
  },
  linkItem: {
    textAlign: 'left',
  },
  viewCardToolsContainer: {
    background: theme.palette.background.reverse,
    maxWidth: '400px',
    margin: `${theme.spacing(2)}px auto 0`,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'sticky',
    bottom: theme.spacing(1),
    boxShadow: '0px 3px 1px -2px rgb(0 0 0 / 20%), 0px 2px 2px 0px rgb(0 0 0 / 14%), 0px 1px 5px 0px rgb(0 0 0 / 12%)',
    borderRadius: theme.spacing(1),
    '& .MuiButtonGroup-contained': {
      boxShadow: '0 0 0 transparent',
    },
  },
  viewCardToolButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    paddingLeft: theme.spacing(4),
    paddingRight: theme.spacing(4),
    paddingTop: theme.spacing(1.5),
    paddingBottom: theme.spacing(1),
    '& .MuiButton-label': {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'column',
    },
  },
  viewCardToolButtonText: {
    textTransform: 'capitalize',
    fontSize: '0.9rem',
  },
  viewCardToolsContainerMob: {
    position: 'sticky',
    bottom: theme.spacing(2),
    right: theme.spacing(2),
    left: 'auto',
    marginLeft: 'auto !important',
    marginRight: '0 !important',
    zIndex: 1202,
  },
  viewCardToolsIconMob: {
    fontSize: 24,
    color: theme.palette.background.default,
  },
  actionButtonBadge: {
    backgroundColor: theme.palette.background.reverse,
    position: 'absolute',
    top: 0,
    right: 0,
    '& .MuiBadge-anchorOriginTopRightRectangle': {
      backgroundColor: theme.palette.background.reverse,
      fontWeight: 'bold',
      border: `3px solid ${theme.palette.background.default}`,
      height: 30,
      minWidth: 30,
      borderRadius: 30,
      fontSize: '0.9rem',
    },
  },
  contactAddedMessage: {
    opacity: 0.5,
    fontSize: '0.8rem',
  },
  viewCardMessage: {
    maxWidth: 400,
    margin: '0 auto',
  },
  passwordFormContainer: {
    maxWidth: 400,
    marginLeft: 'auto',
    marginRight: 'auto',
    marginBottom: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    '& .MuiGrid-item': {
      width: '100%',
    },
  },
  inactiveLogoContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '& svg': {
      fontSize: 100,
    },
  },
}))
